"""fix user model

Revision ID: 95cb99582787
Revises: 18efc7a1988f
Create Date: 2025-01-05 12:01:12.449360

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95cb99582787'
down_revision: Union[str, None] = '18efc7a1988f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('f_name', sa.String(), nullable=True),
                    sa.Column('l_name', sa.String(), nullable=True),
                    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
                    sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
