name: Deploy to VPS

on:
  push:
    branches:
      - master # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies (if needed)
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          # Add commands to install dependencies here (e.g., npm install, pip install)

      # Step 3: Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }} # VPS IP or domain
          username: ${{ secrets.VPS_USER }} # VPS username
          key: ${{ secrets.VPS_SSH_KEY }} # Private SSH key
          port: 2222 # Custom SSH port (change if needed)
          script: |
            set -e # Stop execution on failure
            echo "Deploying application..."

            # Start SSH agent and add the SSH key
            eval "$(ssh-agent -s)" > /dev/null
            ssh-add ~/.ssh/letscode@62.169.28.254 2>/dev/null

            # Navigate to your project directory
            cd ~/www/e-store-fastapi || { echo "Directory not found!"; exit 1; }

            # Pull the latest changes
            git fetch origin
            git reset --hard origin/master

            # Stop existing containers
            docker compose down

            # Build and start new containers
            docker compose build --no-cache
            docker compose up -d

            echo "Deployment complete!"